application: snaptrip
version: 1
runtime: python
api_version: 1

handlers:
- url: /style
  static_dir: static/style
  
- url: /js
  static_dir: static/js

- url: /images
  static_dir: static/images
  
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  
- url: /.*
  script: main.py

